# -*- coding: utf-8 -*-
"""Pycaret_classificatin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tu0SbVcRyUAdeY_z9jzaUwKKeouLgzO3
"""

!pip install pycaret

import pandas as pd
from pycaret.classification import *

from pycaret.datasets import get_data
df = get_data('juice')

setup(df, target='Purchase')

best_model = compare_models()

top3 = compare_models(n_select= 3)

top3

lda = create_model('lda')

plot_model(estimator= lda, plot= 'auc')

plot_model(estimator= lda, plot='feature')

lda = create_model('lda')
ridge = create_model('ridge')
lr = create_model('lr')
#blending 3 models:
blend = blend_models(estimator_list=[ridge,lda,lr])

lgm = create_model('lightgbm')

plot_model(estimator= blend, plot = 'confusion_matrix')

pred = predict_model(blend)

evaluate_model(lr)

