# -*- coding: utf-8 -*-
"""Pycaret_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d_P47WSQsTscchjzP8IxfSxDeMQzGT4i
"""

# !pip install pycaret

from pycaret.regression import *
import pandas as pd

df = pd.read_csv('/home/m-fayzi/Desktop/Pycaret/Datasets/boston.csv')
print(df.info())

"""# Pycaret Regression"""

setup(data=df, target='medv', session_id= 10, train_size=0.9)

models = compare_models()

"""# Create New Model

"""

new_model = create_model('gbr')

"""#Plot Model"""

plot_model(new_model)

"""#Evaluation Model"""

evaluate_model(new_model)

save_model(new_model, 'MY_Model')

my_model = load_model('MY_Model')

predict_model(new_model)

et_model = create_model('et')
tune = tune_model(et_model)

best = automl()
print(best)

evaluate_model(et_model)