# -*- coding: utf-8 -*-
"""Pycaret_Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AzkkL9uBEnCw9p3CHKkvLRY501eC10z2
"""

!pip install pycaret

import pandas as pd
from pycaret.clustering import *

from pycaret.datasets import get_data
df = get_data('jewellery')

setup(df)

kmeans =create_model('kmeans')
print(kmeans)

plot_model(kmeans, plot = 'elbow')

plot_model(kmeans, plot = 'tsne')

plot_model(kmeans, plot='distribution')

evaluate_model(kmeans)

kmeans_df = assign_model(kmeans)
kmeans_df.head()

hierarchical = create_model('hclust')

plot_model(hierarchical, plot='cluster', label=True)